#!/bin/bash
#
# Auxspace avionics application entrypoint for docker
#
# Author: Maximilian Stephan @ Auxspace e.V.
# Copyright (c) 2025 Auxspace e.V.
#

set -e

################################################################################
# Functions                                                                    #
################################################################################

function first_boot_actions() {
  local is_ci_build="${1:-0}"
  # Signal first boot success
  sudo mkdir -p "$(dirname $FIRST_BOOT_TMP_FLAG)"
  sudo touch "$FIRST_BOOT_TMP_FLAG"
}

function build_picotool() {
  if [ ! -d "${PICOTOOL_PATH}/build" ]; then
    mkdir -p "${PICOTOOL_PATH}/build"
  fi

  cd "${PICOTOOL_PATH}/build"
  cmake -DCMAKE_INSTALL_PREFIX=~/.local ..
  make
  make install
}

function build_app() {
  set -e
  local AURORA_BUILD_OUT="${BUILDER_APPLICATION}/build/src"

  echo "[debug]: Building AURORA for platform \"$PICO_BOARD\""

  # compile picotool
  test -x ~/.local/bin/picotool || build_picotool

  # prepare build env
  echo "Running cmake ..."
  cd "${BUILDER_APPLICATION}"
  cmake -S . -B build

  # compile and link project
  echo "Compiling sources ..."
  cmake --build build
  echo "Project compiled. Output is at \"${BUILDER_APPLICATION}/build\"."

  if [ -n "$(find ${AURORA_BUILD_OUT} -maxdepth 1 -name 'aurora.*')" ]; then
    cp -v "${AURORA_BUILD_OUT}"/aurora.* "${BUILDER_APPLICATION}/build/"
  else
    echo "[warning]: No build output found at \"${AURORA_BUILD_OUT}\"!"
  fi
}

function clean_app() {
  set -e

  cd "${BUILDER_APPLICATION}/build"
  make clean
  echo "Build dir cleaned."
}

################################################################################
# Variables                                                                    #
################################################################################

COMMAND=""
declare -a ARGS=()

# Flag that shows if everything has already been initialized.
FIRST_BOOT_TMP_FLAG=${FIRST_BOOT_TMP_FLAG:-"/var/auxspace/first_boot"}

################################################################################
# Run first boot code to setup the environment correctly                       #
################################################################################

if [ ! -f "$FIRST_BOOT_TMP_FLAG" ]; then
  first_boot_actions ${AURORA_CI_BUILDER:+$AURORA_CI_BUILDER}
fi

################################################################################
# Commandline arg parser                                                       #
################################################################################

while [ $# -gt 0 ]; do
  case $1 in
    -b|--pico-board)
      declare -x PICO_BOARD="$2"
      shift 2
      ;;
    build)
      COMMAND=build_app
      shift
      ;;
    clean)
      COMMAND=clean_app
      shift
      ;;
    docs)
      shift
      exec "$BUILDER_APPLICATION/scripts/docs.sh" \
        --src-dir "$BUILDER_APPLICATION/docs" \
        $@
      ;;
    shell)
      COMMAND="/bin/bash"
      # Required for podman build, since in podman container you are root
      if [ ! "${BUILDER_HOME}" = "$HOME" ]; then
        cp "${BUILDER_HOME}/.bashrc" ~/.bashrc
        cp "${BUILDER_HOME}/.bash_aliases" ~/.bash_aliases
      fi
      shift
      ;;
    --*)
      echo "ERROR: No such option: $1"
      exit 1
      ;;
    *)
      echo "ERROR: No such command: ${1}"
      exit 1
      ;;
  esac
done

################################################################################
# Run command                                                                  #
################################################################################

$COMMAND ${ARGS[@]}
