# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: auxspace-rtos
      url-base: git@github.com:AUXSPACEeV

  projects:
    - name: zephyr
      remote: auxspace-rtos
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_rpi_pico   # required by the rpi_pico boards (raspberrypi based)
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)

