# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyr-rtos
      url-base: https://github.com/zephyrproject-rtos/
  defaults:
    remote: zephyr-rtos
  projects:
    - name: zephyr
      remote: zephyr-rtos
      revision: main
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - zephyr
          - cmsis_6    # required by the ARM port for Cortex-M
          - hal_rpi_pico   # required by the rpi_pico boards (raspberrypi based)
          - fatfs      # required for filesystem operations (ff.h)
