# Copyright (c) 2026 Auxspace e.V.
# SPDX-License-Identifier: Apache-2.0
#
# Extra overlay for bench work:
#   west build -b core65/esp32s3/procpu telemetry_logger -- -DEXTRA_CONF_FILE=debug.conf

CONFIG_TELEMETRY_LOGGER_LOG_LEVEL_DBG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_RESET_ON_FATAL_ERROR=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y

CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_THREAD_ANALYZER_AUTO=n
