# common options, which apply to all boards (will be duplicated in board configs)

# Console and Shell
CONFIG_CONSOLE=y
CONFIG_SHELL=y
CONFIG_SENSOR_SHELL=y

# Boot banner
CONFIG_BOOT_BANNER_STRING="Booting AURORA"

# Logging
CONFIG_LOG=y
CONFIG_LOG_FLUSH_SLEEP_US=1000
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_TIMESTAMP_USE_REALTIME=y
CONFIG_LOG_SPEED=y
CONFIG_LOG_THREAD_ID_PREFIX=y
CONFIG_LOG_INFO_COLOR_GREEN=y
CONFIG_LOG_DBG_COLOR_BLUE=y
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=y
CONFIG_LOG_BACKEND_FS_FILE_SIZE=100000000
# CONFIG_LOG_BACKEND_FS_APPEND_TO_NEWEST_FILE is not set
CONFIG_LOG_BACKEND_UART_BUFFER_SIZE=32
# CONFIG_LOG_MEM_UTILIZATION is not set
CONFIG_LOG_CMDS=y
CONFIG_LOG_RATELIMIT_INTERVAL_MS=500

# State machine
CONFIG_AURORA_STATE_MACHINE=y

# Data logger
CONFIG_DATA_LOGGER=y

CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
