# common options, which apply to all boards (will be duplicated in board configs)

# Console and Shell
CONFIG_SHELL=y
CONFIG_SENSOR_SHELL=y

# Boot banner
CONFIG_BOOT_BANNER_STRING="Booting AURORA"

# Logging
CONFIG_LOG=y
CONFIG_LOG_FLUSH_SLEEP_US=1000
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_TIMESTAMP_USE_REALTIME=y
CONFIG_LOG_SPEED=y
CONFIG_LOG_THREAD_ID_PREFIX=y
CONFIG_LOG_INFO_COLOR_GREEN=y
CONFIG_LOG_DBG_COLOR_BLUE=y
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=y
# CONFIG_LOG_BACKEND_FS_APPEND_TO_NEWEST_FILE is not set
# CONFIG_LOG_MEM_UTILIZATION is not set
CONFIG_LOG_CMDS=y
CONFIG_LOG_RATELIMIT_INTERVAL_MS=500

# State machine
CONFIG_AURORA_STATE_MACHINE=y
CONFIG_AURORA_STATE_MACHINE_SHELL=y

CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_ZBUS_MSG_SUBSCRIBER_NET_BUF_POOL_SIZE=32
