CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024
CONFIG_CONSOLE=y
CONFIG_APOGEE_DETECTION=y
CONFIG_AURORA_STATE_MACHINE=y
CONFIG_BOOT_BANNER_STRING="Booting AURORA"
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_UART_CONSOLE=y
CONFIG_SENSOR=y
CONFIG_AURORA_SENSORS=y
CONFIG_IMU=y
CONFIG_BARO=y
CONFIG_SENSOR_SHELL=y
# CONFIG_COMMON_LIBC_REMOVE is not set
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y
CONFIG_FILE_SYSTEM_SHELL_TEST_COMMANDS=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_TIMESTAMP_USE_REALTIME=y
CONFIG_LOG_SPEED=y
CONFIG_LOG_THREAD_ID_PREFIX=y
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=y
CONFIG_LOG_BACKEND_FS=y
CONFIG_LOG_BACKEND_FS_DIR="MMC:/logs"
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_CMDS=y
CONFIG_SHELL=y
CONFIG_USB_CONSOLE_SHELL=y
