# Copyright (c) 2026 Auxspace e.V.
# SPDX-License-Identifier: Apache-2.0
#
# Extra overlay for bench work:
#   west build -b tel65 abby -- -DEXTRA_CONF_FILE=debug.conf

CONFIG_ABBY_LOG_LEVEL_DBG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_THREAD_NAME=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_THREAD_ANALYZER_AUTO=n

CONFIG_ASSERT=y
