#!/usr/bin/env python3
# Copyright (c) 2025-2026 Auxspace e.V.
# SPDX-License-Identifier: Apache-2.0
#
# Convert a recorded aurora flight CSV (as produced by the data logger's
# CSV converter) into a generated C source file with embedded sample
# arrays. Consumed by the replay-mode fake_sensors backend so simulated
# autotests can be driven by real flight data instead of a synthetic
# profile.
#
# Output schema (see fake_sensors_replay.c):
#
#   struct replay_imu_sample  { uint64_t t_ns; float x, y, z; };
#   struct replay_baro_sample { uint64_t t_ns; float pres_kpa, temp_c; };
#
#   const struct replay_imu_sample  replay_accel[REPLAY_ACCEL_LEN];
#   const struct replay_imu_sample  replay_gyro[REPLAY_GYRO_LEN];
#   const struct replay_baro_sample replay_baro[REPLAY_BARO_LEN];

import argparse
import csv
import sys
from pathlib import Path


def parse_csv(path):
    accel, gyro, baro = [], [], []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                ts = int(row["timestamp_ns"])
            except (KeyError, ValueError):
                continue
            ax = row.get("accel_x", "")
            if ax != "":
                accel.append((ts, float(ax),
                              float(row["accel_y"]),
                              float(row["accel_z"])))
                gx = row.get("gyro_x", "")
                if gx != "":
                    gyro.append((ts, float(gx),
                                 float(row["gyro_y"]),
                                 float(row["gyro_z"])))
            pres = row.get("baro_pres", "")
            if pres != "":
                temp = row.get("baro_temp", "") or "0"
                baro.append((ts, float(pres), float(temp)))
    return accel, gyro, baro


def emit_imu_array(name, samples, t0):
    out = [f"const struct replay_imu_sample {name}[] = {{"]
    for t, x, y, z in samples:
        out.append(f"\t{{ {t - t0}ULL, {x:.6f}f, {y:.6f}f, {z:.6f}f }},")
    out.append("};")
    out.append(f"const size_t {name}_len = ARRAY_SIZE({name});")
    return "\n".join(out)


def emit_baro_array(name, samples, t0):
    out = [f"const struct replay_baro_sample {name}[] = {{"]
    for t, p, temp in samples:
        out.append(f"\t{{ {t - t0}ULL, {p:.6f}f, {temp:.6f}f }},")
    out.append("};")
    out.append(f"const size_t {name}_len = ARRAY_SIZE({name});")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="flights.csv from data_logger")
    ap.add_argument("--output", required=True, help="generated .c output path")
    args = ap.parse_args()

    accel, gyro, baro = parse_csv(args.input)
    if not accel or not gyro or not baro:
        print("error: input CSV is missing accel/gyro/baro samples",
              file=sys.stderr)
        return 1

    t0 = min(accel[0][0], gyro[0][0], baro[0][0])

    header = (
        "/* AUTO-GENERATED by tools/gen_flight_replay.py.\n"
        " * Do not edit. Re-run the build to regenerate.\n"
        f" * Source: {Path(args.input).name}\n"
        f" * Samples: accel={len(accel)} gyro={len(gyro)} baro={len(baro)}\n"
        f" * Span:    {(max(accel[-1][0], gyro[-1][0], baro[-1][0]) - t0)/1e9:.3f} s\n"
        " */\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n"
        "#include <zephyr/sys/util.h>\n"
        '#include "fake_sensors_replay.h"\n'
    )

    body = "\n\n".join([
        emit_imu_array("replay_accel", accel, t0),
        emit_imu_array("replay_gyro", gyro, t0),
        emit_baro_array("replay_baro", baro, t0),
    ])

    Path(args.output).write_text(header + "\n" + body + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
