# Simple Job to build the AURORA Docs
name: Build AURORA Docs

on:
  push:
    branches: [ "main", "next" ]
  schedule:
  - cron: "0 2 * * *"

jobs:
  build-docs:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Fetch Dependencies
      # Get dependencies for Aurora docs
      run: |
        git submodule update --init
        cd src/sdk && git submodule update --init && cd ..
        ./scripts/docs.sh --src-dir "./docs" setup

    - name: Build HTML Docs
      # Build HTML docs
      run: ./run.sh docs html

    - name: Upload HTML
      uses: actions/upload-artifact@v4.6.2
      with:
        # Artifact name
        name: static-webpage
        path: docs/_build/html/
        if-no-files-found: error
        retention-days: 1
