# Simple Job to build AURORA for multiple platforms
name: Build AURORA for multiple platforms

on:
  push:
    branches: [ "main", "next" ]
  pull_request:
    branches: [ "main", "next" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 4 configurations:
      # 1. <Linux, Release, Sensor Board (custom Auxspace hardware)>
      # 2. <Linux, Release, Test Board (used for unit tests (TODO))>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        board: [sensor_board, test]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      # Build AURORA with the given configuration..
      run: AURORA_CI_BUILD=1 ./run.sh --board ${{ matrix.board }} build

    - name: Upload Binaries
      uses: actions/upload-artifact@v4.6.2
      # Only upload artifacts of boards, not tests (might not generate uf2)
      if: "${{ matrix.board != 'test' }}"
      with:
        # Artifact name
        name: binaries
        path: |
          build/aurora.bin
          build/aurora.elf
          build/aurora.uf2
        if-no-files-found: warn
        retention-days: 7
